// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ikbb9vCE_cPi4l2dM8SDUz8TDWLuuz4',
    appId: '1:543007245388:web:8f43a5262a359fed9c60e9',
    messagingSenderId: '543007245388',
    projectId: 'ets-59b6c',
    authDomain: 'ets-59b6c.firebaseapp.com',
    storageBucket: 'ets-59b6c.firebasestorage.app',
    measurementId: 'G-0G5E9CE5RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtHrk1T8gwhypi_WrU05S-IlqVqA33_KA',
    appId: '1:543007245388:android:1280eab067c1ed319c60e9',
    messagingSenderId: '543007245388',
    projectId: 'ets-59b6c',
    storageBucket: 'ets-59b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQo16rVGUFgzwxcRrRzf5xLFkFmQGGhi4',
    appId: '1:543007245388:ios:817fffccdb6807469c60e9',
    messagingSenderId: '543007245388',
    projectId: 'ets-59b6c',
    storageBucket: 'ets-59b6c.firebasestorage.app',
    iosBundleId: 'com.example.ets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQo16rVGUFgzwxcRrRzf5xLFkFmQGGhi4',
    appId: '1:543007245388:ios:817fffccdb6807469c60e9',
    messagingSenderId: '543007245388',
    projectId: 'ets-59b6c',
    storageBucket: 'ets-59b6c.firebasestorage.app',
    iosBundleId: 'com.example.ets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ikbb9vCE_cPi4l2dM8SDUz8TDWLuuz4',
    appId: '1:543007245388:web:f654714472cf9f849c60e9',
    messagingSenderId: '543007245388',
    projectId: 'ets-59b6c',
    authDomain: 'ets-59b6c.firebaseapp.com',
    storageBucket: 'ets-59b6c.firebasestorage.app',
    measurementId: 'G-Y3XT046HZ2',
  );
}
