// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdM0SuajvoPd1vrhAJQZXnewk01INn854',
    appId: '1:727000712765:web:f031a1cc444decd4594c54',
    messagingSenderId: '727000712765',
    projectId: 'fir-crud-basics-1c48e',
    authDomain: 'fir-crud-basics-1c48e.firebaseapp.com',
    storageBucket: 'fir-crud-basics-1c48e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ErblTFZarFFswm3STk2Qfn6DFUYTz8k',
    appId: '1:727000712765:android:4059f216948be478594c54',
    messagingSenderId: '727000712765',
    projectId: 'fir-crud-basics-1c48e',
    storageBucket: 'fir-crud-basics-1c48e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2CYwatxQjvsTU3gliWthyaAuqDfju8zE',
    appId: '1:727000712765:ios:aa2a61c6f0141db4594c54',
    messagingSenderId: '727000712765',
    projectId: 'fir-crud-basics-1c48e',
    storageBucket: 'fir-crud-basics-1c48e.firebasestorage.app',
    iosBundleId: 'com.example.app4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2CYwatxQjvsTU3gliWthyaAuqDfju8zE',
    appId: '1:727000712765:ios:aa2a61c6f0141db4594c54',
    messagingSenderId: '727000712765',
    projectId: 'fir-crud-basics-1c48e',
    storageBucket: 'fir-crud-basics-1c48e.firebasestorage.app',
    iosBundleId: 'com.example.app4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdM0SuajvoPd1vrhAJQZXnewk01INn854',
    appId: '1:727000712765:web:34f42deb90f8a031594c54',
    messagingSenderId: '727000712765',
    projectId: 'fir-crud-basics-1c48e',
    authDomain: 'fir-crud-basics-1c48e.firebaseapp.com',
    storageBucket: 'fir-crud-basics-1c48e.firebasestorage.app',
  );

}